server:
  port: 8082
aliyun:
  oss:
    bucketName: "zerowdd-qingcheng"
    accessKeyId: "LTAI4FxtgTG9eBLHrkBsGC4d"
    accessKeySecret: "n7PimBiLqJUsmSppr7xtd12L3y7uop"
    #OSS对应的区域
    endpoint: "oss-cn-beijing.aliyuncs.com"
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  application:
    name: upload-service

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期

