server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.159.138
    username: guest
    password: guest
    virtual-host: /
  redis:
    host: 192.168.159.138
aliyun:
  sms:
    accessKeyId:
    accessKeySecret: 
    singnName: "商小惠"
    verifyCodeTemplate: "SMS_176914322"
